### PR TITLE
Add support for reading migrations from the classpath

### PR DESCRIPTION
**Pull request by cdorrat**
This pull request adds the ability to load migrations from the classpath, it allows you to package migrations with a jar/uberjar.
 
To automatically run migrations on app start-up add `:resource-paths ["migrations"]` to project.clj

and call the following code at application startup:
(binding [mf/*migration-dir* "."]
    (dbm/migrate my-db-config))

I can ship migrations in an uberjar and have them automatically run without user intervention, very handy for automatically creating schemas on deploy in docker.

Migrations are loaded from both the local filesystem and the classpath (directories and jars).
If the same migration exists in the local filesystem and the classpath the classpath version will be preferred.

### CODE REVIEW

**Comment by ckuttruff** [comment]
@cdorrat Thanks so much for the contribution.  Working til about 5, but I'll take a look / test things out around then.

@icambron sorry for delay on reviewing your PR as well... does this PR satisfy your requirements as well?  Makes sense, but given my limited experience shipping jars, would be great to get your feedback as well.

Will go through some testing later today.

Cheers!

**Comment by ckuttruff** [comment]
Any chance we could generate the jar we need for the tests within the test suite?  We could even cache it for subsequent use (so it doesn't slow down the suite), but it seems preferable to having a mystery jar in the source.  Would also be useful in terms of understanding the usage

Thoughts?

**Comment by icambron** [comment]
I think it's probably equivalent; it just uses a different library to list the jar's files. I don't really have an opinion on which one's better.

FWIW, I've been using mine in prod for a while now.

**Comment by cdorrat** [comment]
I did think about generating the jar for test but the best I could come up with was
something like "with-profile test-data jar" to create the jar then adding a run-test a target as "do create-test-jar, test". I'm just about to head off to work & have other commitments tonight but I can look at it tomorrow.

I just had a look at the other pr, it does seem equivalent, just missing any tests.

**Comment by cdorrat** [comment]
On second thoughts there is a slight difference in approach, the @icambron  pr chooses either a directory (preferred) or class path, this one merges the two & removes duplicates (with classpath preferred). 
Either will work for my purposes.

**Comment by cdorrat** [comment]
Updated the build to automatically create the test jar & removed the binary jar file from test

**Comment by ckuttruff** [comment]
@cdorrat great!  thanks a lot.... reviewing now

**Comment by ckuttruff** [comment]
@cdorrat Thanks again; really appreciate the additional functionality, tests, tweak regarding the jar file.

Nice work!

**Comment by ckuttruff** [comment]
Just pushed up 0.3.7 to clojars.

**Pull request merged**
